"""fightsdb table created

Revision ID: f0deb4081677
Revises: 976ea42f93c1
Create Date: 2022-05-11 15:09:28.541768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0deb4081677'
down_revision = '976ea42f93c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_fighter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_fighter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'participantsDB', ['blue_fighter_id'], ['participant_id'])
        batch_op.create_foreign_key(None, 'participantsDB', ['red_fighter_id'], ['participant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('blue_fighter_id')
        batch_op.drop_column('red_fighter_id')

    # ### end Alembic commands ###
